FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps

COPY packages ./packages

#insatall dependencies

RUN npm install


# run build and prebuild

RUN npm run build

#start the user app

CMD ["npm", "run", "start-user-app"]